### ISSUE TITLE
Cooperation

### ISSUE THREAD

**Issue by hediet** [rmp135/sql-ts#1]
Hi,
maybe we should cooperate: I recently wrote a typed [SQL builder](https://github.com/hediet/ts-typed-sql) ([live demo](https://hediet.github.io/ts-typed-sql/)) and I am still missing some code generation features which you seem to have implemented.

Maybe you noticed as well that knex does not work very well together with typescript and are looking for a better alternative to knex?

**Comment by rmp135** [comment]
Of course, I’d be more than happy to help. 

I’m assuming you’re looking for a generic system for retrieving database schemas and spitting out a definition / interface file.
