### ISSUE TITLE
Column names with trailing underscore + number (eg. "_2") erroneously converted when camelized

### ISSUE THREAD

**Issue by briangonzalez** [rmp135/sql-ts#104]
We have a column called `address_line_1` and when converted, this library generates `addressLine_1` though I'd expect `addressLine1`

This is a recent regression, as former versions worked fine.

The issue seems to be with the library used called [change-case](https://www.npmjs.com/package/change-case).

See example below:

https://npm.runkit.com/change-case

```js
const changeCase = require("change-case")
changeCase.camelCase("address_line_1") 
// => actual: addressLine_1; expected addressLine1
```

**Comment by rmp135** [comment]
Apologies for the delay. 

Interesting behaviour. There's actually a setting in the library to merge the numbers which when running the tests exhibits the desired behaviour. I'll get a fix out soon.
