### ISSUE TITLE
Enum key 0 isn't recognised as numeric member

### ISSUE THREAD

**Issue by frankwaldal** [rmp135/sql-ts#107]
When generating an Enum with numeric keys, `0` isn't recognised as a numeric member and doesn't get prefixed.

From what I can gather it comes from https://github.com/rmp135/sql-ts/commit/6f4524280bdcfd7c06742cd12af5a6b33dff9b89 where `generateEnumKey` does a `!toNumber(newKey)` check, and since `!0 === true`, it just returns `newKey`, instead of prefixing it as with other numeric members.

**Comment by rmp135** [comment]
Foiled again by JavaScript type coercion. I'll get a fix out as soon as I can, thanks for raising.

**Comment by frankwaldal** [comment]
Thanks a lot for quick reply, fix, and a great package :)
