### ISSUE TITLE
Feature Request: json-schema generation

### ISSUE THREAD

**Issue by jsbrain** [rmp135/sql-ts#109]
Ever thought about pairing it with [typebox](https://github.com/sinclairzx81/typebox) to generate the types?

This would result in not only getting the types, but also a json-schema which could be used for all sorts of input and output validation, basically "for free".

The only project I've seen so far doing it is [prisma-typebox-generator](https://github.com/adeyahya/prisma-typebox-generator) which only covers some of the required generation and also is dependent on [prisma](https://github.com/prisma/prisma) but I think having a project like `sql-ts` that works for multiple DBs and also generating json schemas for the models and input/query models as well would be incredibly powerful and useful.

I'm eager to hear your opinion 🙌

**Comment by rmp135** [comment]
It's not something I've actively looked into and probably won't pursue it.

It should be possible to take the output of `toObject` and parse it in a way to generate the typebox types.

If someone does make a tool that combines these libraries I'll gladly link it in the readme.
