### ISSUE TITLE
toObject Verbosity

### ISSUE THREAD

**Issue by MrDesjardins** [rmp135/sql-ts#116]
First of all, great tool!

I haven't found in the documentation a way to avoid to see a lot of data in the terminal when using the following code:

```
import sqlts, { Config } from "@rmp135/sql-ts";
sqlts.toObject(config, db).then((definition) => { .... }
```
Is there a configuration that need to be passed if I want to have no output in the terminal that is executing that code?

**Comment by rmp135** [comment]
Sorry for the long delay in responding. I've ran the above but I don't receive anything in the console. 

Which database provider  were you using and what sort of data was being printed?

**Comment by MrDesjardins** [comment]
Hello @rmp135,

I should have updated that ticket. In the last three months, I have found the issue.

The database provider is knex using the client `mysql2`.
Here is a more elaborated configuration snippet:

```
import sqlts, { Config } from "@rmp135/sql-ts";
import knex, { knex } from "knex";

const config: Config = {debug: false};
const db = knex({
    client: "mysql2",
    connection: {
       // Snip
    },
    debug: true // <------------------ Here
});

sqlts.toObject(config, db).then((definition) => { .... }
```
There is a `debug` property on the `knex` library, not the sql-ts. That one was set using an environment variable. Once it was turned to `false`, the script running sql-ts was not outputting. Thus, the issue was around knex and not sql-ts. I'll close this ticket.

Thanks for following up.
