### ISSUE TITLE
Option to use `const assertions` instead of `enums`

### ISSUE THREAD

**Issue by marvin-kolja** [rmp135/sql-ts#119]
Hey @rmp135, first of all, thank you for this amazing library. I've been using it in my project and it works like a charm.

I recently [came across](https://www.youtube.com/watch?v=jjMbPt_H3RQ) a more javascript native way of implementing enums in an enum-like structures. Libraries like the [graphql typescript generator](https://the-guild.dev/graphql/codegen/plugins/typescript/typescript) support an option to enable this.

An example:

```ts
// normal enum
enum EnumStatus {
    PENDING: 'pending',
    FAILED: 'failed',
    SUCCESS: 'success'
}

const status: EnumStatus = EnumStatus.PENDING

// enum like structure (const assertion)
export const ConstAssertionStatus = {
    PENDING: 'pending',
    FAILED: 'failed',
    SUCCESS: 'success'
} as const

export type ConstAssertionStatus =
    typeof ConstAssertionStatus[keyof typeof ConstAssertionStatus]

const status: ConstAssertionStatus = ConstAssertionStatus.SUCCESS
// but the following is also possible
const status: ConstAssertionStatus = 'success'
```

I just wanted to hear your thoughts on this. If you like the idea to have an option to replace enums with the mentioned alternative I would be willing to open a PR.

Cheers! and wish a good Christmas time 🎄

**Comment by rmp135** [comment]
It's actually quite easy to generate the above enum definitions.

In the template replace the [enum loop](https://github.com/rmp135/sql-ts/blob/master/src/template.handlebars#L20-L26) with the following.

```handlebars
{{#each enums as |enum|}}
export const {{convertedName}} = {
{{#each values as |value|}}
  '{{value.convertedKey}}': {{handleNumeric value.value}},
{{/each}}
} as const;
export type {{convertedName}} =
  typeof {{convertedName}}[keyof typeof {{convertedName}}]
{{/each}}
```

I'm a little weary of changing this behaviour, I prefer to keep it as simple as possible for most users. I can add it the docs though as an alternative method of creating enums.

**Comment by elyobo** [comment]
Worth noting that as of TS 5.8 the `erasableSyntaxOnly` flag is available which prohibits enums as non-erasable syntax, so this might crop up again.
