### ISSUE TITLE
Upgrade knex version

### ISSUE THREAD

**Issue by filenwind** [rmp135/sql-ts#120]
Knex currently is 2.3.0

But sql-ts using ^1.0.3

Which cause the typing wrong when I put the knex instance to param

`
Type 'import("{projectRoot}/node_modules/knex/types/index").Knex.Value' is not assignable to type 'import("{projectRoot}/node_modules/@rmp135/sql-ts/node_modules/knex/types/index").Knex.Value'.
`

Or set knex as peer dependency?

Thanks!

**Comment by rmp135** [comment]
Merged #114 which should fix this issue.
