### ISSUE TITLE
"database" and "tables" attributes ignored in mysql.json

### ISSUE THREAD

**Issue by tofsjonas** [rmp135/sql-ts#122]
It just grabs all the tables in all the databases. 😢

**Comment by rmp135** [comment]
Ah, MySQL disregards the `database` when we fetch table schema. 

From my testing, placing it outside the `connection` block won't do anything. You want to use `schemas: ["my_database"]` to only fetch schema info from a particular database.

I'll update the docs to reflect this, thanks.

**Comment by tofsjonas** [comment]
You are right, placing it outside doesn't work for me either. Don't know why I thought it did 🤷

`schemas: ["my_database"] ` works like a charm though!

Thanks! 🙏
