### ISSUE TITLE
[Discussion] ENUM handling in MySQL

### ISSUE THREAD

**Issue by VanTanev** [rmp135/sql-ts#123]
We've had trouble in getting the behavior we desire from ENUMs, and have ended up using type overrides instead of relying on the generation.

In practice, we believe that a string literal union should be the preferred type to be generated for an enum column, rather than a TypeScript enum.

This is because TypeScript enums are somewhat of an aberration in TS - there are one of only 3 structures that do not get erased when compiling to JavaScript, but instead need to be outputted as bespoke JS (the other two are namespaces and decorators). This introduces possible problems with differences between the output of the official TS compiler, vs babel, vs esbuild, vs swc. 

Additionally, they have a behavior similar to interfaces, where you can define an enum multiple times, and the declarations will be merged instead of erroring out.

We've found that for representing an enum database column as a string literal union is preferable.

Is there a way for sql-ts to generate a string literal union type for enums?

**Comment by seanim0920** [comment]
I also need this

**Comment by rmp135** [comment]
Apologies for a _very_ long delay but version 2.0 has support for MySQL enums, generating a string union type for that column. 

However the union type will be defined on each column separately, even if they match.

**Comment by VanTanev** [comment]
> However the union type will be defined on each column separately, even if they match.

This is a better approach than trying to combine them! 

Thank you!
