### ISSUE TITLE
singularTableNames=true on a table called `address` results in in wrong type names DbAddresSchema

### ISSUE THREAD

**Issue by mjsilva** [rmp135/sql-ts#130]
due to this https://github.com/rmp135/sql-ts/blob/1.18.0/src/TableTasks.ts#L80-L81 if you have a table named `address` which is valid singular the output type names become `Addres` which is wrong.

**Comment by rmp135** [comment]
This has been fixed version 2.0. It's now relying on the pluralize library which handles singularising words must better than my very rudimentary approach.
