### ISSUE TITLE
Please add generated timestamp at top

### ISSUE THREAD

**Issue by Longwater1234** [rmp135/sql-ts#132]
Thanks for creating this tool. I would be extremely grateful if after the comment "This files was generated by a tool..." you also add another comment: Timestamp in UTC (or even better: `localTime+UTC` offset)

```JS
// Generated YYYY-mm-dd HH:mm:ss:zz-08:00
(for PST)
```

**Comment by rmp135** [comment]
I won't be adding this to the default template as it's a bit bespoke. 

However, if you generate the output programmatically, you can use a user [template](https://rmp135.github.io/sql-ts/#/?id=template) and add the current time in whatever format you would like to the [custom](https://rmp135.github.io/sql-ts/#/?id=custom) config option, available as `{{custom.timestamp}}` (for example) in the template.
