### ISSUE TITLE
How to put interfaces into each own files?

### ISSUE THREAD

**Issue by mbektimirov** [rmp135/sql-ts#135]
Is it possible to have exported interfaces separated by files with the rule "**one table - one `.ts` file**"?

**Comment by rmp135** [comment]
By default, no. 

However, by careful manipulation of the object definition you can extract each table and save them as files manually. I can imagine this won't work with enums as it requires linkage between definitions which will now be broken.

This effectively goes through each table of each schema and creates a database that contains only that table. Then it builds a TypeScript file with that database. It uses the 2.0 syntax.

```ts
const asObject = await Client
  .fromConfig(config)
  .fetchDatabase(db)
  .toObject()

const tablesAsDatabases = asObject.schemas.flatMap(schema => {
  return schema.tables.map(table => {
    return {
      ...schema,
      tables: [table]
    }
  })
})
.map(schema => {
  return {
    schemas: [schema]
  }
})

for (const database of tablesAsDatabases) {
  const ts = await Client.fromObject(database, config).toTypescript()
  await fs.writeFile(`./${database.schemas[0].tables[0].name}.ts`, ts)
}
```
