### ISSUE TITLE
Add option to use `type` intstead of `interface`

### ISSUE THREAD

**Issue by SuperKXT** [rmp135/sql-ts#136]
Some prefer `type` over `interface` to define object types.
While I have no strong feelings about this, I maintain some projects with lint rules to prevent the use of `interface`.

It will be helpful to add an option to generate with `type`.

**Comment by rmp135** [comment]
Interesting. I won't add it right now, as types are subtly different enough that they collide (e.g. the `extends` config option would need handling / ignoring). 
I'll say, for now, use a custom template if you prefer using types.
