### ISSUE TITLE
Mapping bytea[] to Uint8Array[]

### ISSUE THREAD

**Issue by pct-cclausen** [rmp135/sql-ts#137]
I have a table that contains a bytea[], which in Typescript needs to be a Uint8Array[].

I've tried this custom typeMap entry:

`"Uint8Array[]": ["bytea[]"]`

However, sql-ts still produces "any".

Are array values in my tables not supported? This is on postgres.

**Comment by rmp135** [comment]
The internal name for a `bytea[]` type is `_bytea`. The correct config option should be:

`"Uint8Array[]": ["_bytea"]`
