### ISSUE TITLE
[SQLite] Sort generated enums so it is stable with each generation

### ISSUE THREAD

**Issue by hc-12** [rmp135/sql-ts#138]
Related to the issue found at https://github.com/rmp135/sql-ts/issues/88.

I am encountering an inconsistency with the ordering of enums generated using `tableEnums`. The order of the enums seems to change with every TypeScript generation. Is there a way to ensure that the order of enums remains constant across generations?

**Comment by rmp135** [comment]
Odd. I'm unable to recreate this but I can add an order by clause to the table enum query to fetch in value order, such that it won't change.

**Comment by hc-12** [comment]
> Odd. I'm unable to recreate this but I can add an order by clause to the table enum query to fetch in value order, such that it won't change.

Thanks for your assistance! Could you also add a distinct keyword in the select statement to ensure unique values are returned?

**Comment by rmp135** [comment]
No, that would be a data issue. If you have duplicate values, make a view that returns the unique results and use that as the enum table instead.
