### ISSUE TITLE
Most columns in interface are optional, even when NOT NULL

### ISSUE THREAD

**Issue by garybernhardt** [rmp135/sql-ts#16]
First, thanks for making this library. It fills a huge gap and worked right out of the box.

A summary:

* sql-ts makes any column without a default value optional in the generated interface.
* I'm using the generated interfaces in my app's model layer.
* Most columns don't have defaults, so they end up optional.
* This means that every attribute access from TypeScript has to be conditional. I have to narrow the column's type from (e.g.) `string | undefined` to just `string`.

Here's a concrete example. I have this table (irrelevant columns elided):

```
                                           Table "public.users"
      Column      |            Type             | Collation | Nullable |              Default
------------------+-----------------------------+-----------+----------+-----------------------------------
 id               | integer                     |           | not null | nextval('users_id_seq'::regclass)
 email            | text                        |           | not null |
 auth_token       | text                        |           |          |
[...]
```

which generates this interface, using sql-ts 1.1.0:

```
export interface Iusers {
  id: number 
  email?: string 
  auth_token?: string | null 
  [...]
}
```

The optionality of `email` and `auth_token` is surprising to me at a conceptual level. In order to successfully insert, we have to provide an `auth_token`, so I want it to be required in the interface. Likewise, any record that we pull from the database will definitely have an `auth_token`, so I want it to be non-optional in the interface there too.

On the read side, this causes practical problems. For example, the `email` column above is `NOT NULL` in the database, so it's always present. But this code:

```
    const email: string = user.email
```

fails to type check:

```
src/backend/db/user.ts(187,11): error TS2322: Type 'string | undefined' is not assignable to type 'string'.
```

If anything, I'd expect the opposite of this optional behavior: if a column has a default value, then it's not required on insert, so it can be optional in the inserting interface. But that still doesn't help with the reading problem shown above.

It looks like this behavior was intentional, because the postgres/mysql/mssql adapters all do it. But I'm curious about the motivation and whether you'd consider a change to it.

I see that this optionality issue was brought up in #9, where the `propertyOptionality` option was introduced. However, that option was later removed in commit 18fc667.

**Comment by rmp135** [comment]
Ah, it appears to be a bug in the template. You're right, it's doing the exact opposite of what it's meant to do. Database fields with identity / defaults are meant to be marked as optional in the interface and all others required, I'll push an update for this ASAP.

Column optionality was removed in favor of the template system. I didn't want to overload the user with configuration options and kept the ones I felt were most useful.

**Comment by Mika83AC** [comment]
Sorry, but I'm not sure how to deal with this now.

Setting `"propertyOptionality": "required",` in config doesn't help (any more?). So how to make these NOT NULL fields with a default value not optional in the typing as they are not optional at all?

Thx :)

**Comment by rmp135** [comment]
To make all fields required, copy the template.handlebars file into a folder and remove the question mark on line 7. Use the [template](https://github.com/rmp135/sql-ts#template) option to specify the new template.
