### ISSUE TITLE
sql-ts: command not found

### ISSUE THREAD

**Issue by Domiserver** [rmp135/sql-ts#18]
Dear sql-ts community,

I'm having this issue but cannot figure out how to fix it.

To reproduce the error:
1) npm install sql-ts
2) I verified sql-ts was installed inside node_modules
3) Created a configuration file:  mysql.json 
{
    "dialect":"mysql",
    "connection": {
      "host": "localhost",
      "user": "root",
      "password": "myPassword",
      "database" : "my_database"
    }
  }
4) I ran in the terminal the following command:
#   sql-ts -c ./config.json
and then the error:
#   sql-ts: command not found

Thanks so much for your help with this issue.

**Comment by rmp135** [comment]
Try ’npx sql-ts -c ./config.json’. You’re trying to run the global path when it’s installed locally. 

I wrote a general usage guide but in hindsight it was probably _too_ general. If that works I’ll put it in the guide. npx was shipped with node 5.2 so it should be available on most installations.

**Comment by kevinsherman** [comment]
I'm getting the same issue... and when I run the suggested command, I'm getting: `npx: installed 3 in 1.094s \ncommand not found: sql-ts`

**Comment by rmp135** [comment]
My mistake, I keep forgetting to put the namespace into the install command. Try `npx @rmp135/sql-ts`.

**Comment by rmp135** [comment]
I'm going to close this for now. If you're still having issues, feel free to reopen.
