### ISSUE TITLE
Support for materialized views for postgres

### ISSUE THREAD

**Issue by mhuconcern** [rmp135/sql-ts#26]
Is there support for materialized views for postgres? If so how do I use it?

I was using schemats before but it also doesn't support it. It will be great if can do it.

**Comment by rmp135** [comment]
It may be possible. I don't actually use postgres so I'll have a dig around.

**Comment by rmp135** [comment]
I've added this into the 1.4.0-beta.0 release. You should be able to find it on npm by exact version name. 

I would greatly appreciate it if you could take some time to test it as it completely changes how PostgreSQL fetches schema information.

**Comment by mhuconcern** [comment]
Cool. Ill test it out and let u know if it works
