### ISSUE TITLE
bug in some generated column names

### ISSUE THREAD

**Issue by saostad** [rmp135/sql-ts#32]
Hi, I am working on a very big DB and find out some problems with column names that are valid in the SQL server but not in js/ts.
Here is a list of generated problems: 
- `SubCO/POCONum: number | null`
- `P-UN: string`
- `Receiver#: string | null`
- `L-%Comp: number | null`

I think there are a few solutions:
- validate field names before generating them 
- generate all fields in string format "FIELD_NAME" (better performance)
and then maybe we can run prettier on the generated file to standardize the output.

**Comment by saostad** [comment]
I have created a pull request to fix the problem: https://github.com/rmp135/sql-ts/pull/33

**Comment by rmp135** [comment]
Thanks for the pull request. I'll take a look over it and merge it in.
