### ISSUE TITLE
Add functionality to generate some general functions

### ISSUE THREAD

**Issue by saostad** [rmp135/sql-ts#34]
Thanks for the awesome work.
I have extended a little the functionality of this library to generate some functions to query data with knex alongside interfaces for each table. here is the link to the [repository](https://github.com/saostad/sql-ts-knex-generator) please let me know if you are interested to merge that to yours. 
I can create a pull request with my changes.

**Comment by rmp135** [comment]
Thanks for the pull request. I want to keep this tool generic, we're only interested in generating data models. Database access logic is up to the user.
