### ISSUE TITLE
Support for importing custom types

### ISSUE THREAD

**Issue by albertreed** [rmp135/sql-ts#38]
Is there currently a way to provide a list of imports to append to the top of the generated file? I  have a `JSONB` column called `data` in a postgres database that I would like to type. Providing this to the config works:
```
  "typeOverrides": {
    "public.table.data": "{someValue: number}"
  }
```
but it would be more elegant to supply a type via an import at the top of the generated file so that the `typeOverrides` could read:
```
  "typeOverrides": {
    "public.table.data": "MyCustomType"
  }
```

**Comment by rmp135** [comment]
You can edit the template to include the import and use the [template](https://github.com/rmp135/sql-ts#template) config option. Your second example should then work.

**Comment by albertreed** [comment]
This worked great for me. Thanks!
