### ISSUE TITLE
"id" column generating as optional in typescript

### ISSUE THREAD

**Issue by albertreed** [rmp135/sql-ts#39]
In Postgres, I have a `NOT NULL` column. This column is also `PRIMARY KEY`.
```
     Column     |            Type             | Collation | Nullable |      Default       | Storage  | Stats target | Description
----------------+-----------------------------+-----------+----------+--------------------+----------+--------------+-------------
 id             | uuid                        |           | not null | uuid_generate_v4() | plain    |              |
```

The generated typescript is correctly turning the `uuid` into a `string`, but not catching the `not null` bit. 
```
id?: string
````
This is strange because other columns which are also `not null` are being marked correctly. Any idea how I might work around the problem?

Thanks!

**Comment by rmp135** [comment]
This is working as intended. Columns with default values are marked as optional as you don't have to include them when performing inserts. If you would like default values to not be marked as such, you can remove the `{{#if optional}}?{{/if}}` from the template.

**Comment by albertreed** [comment]
Got it, thanks a ton.
