### ISSUE TITLE
Support for more robust singularization

### ISSUE THREAD

**Issue by Bradleykingz** [rmp135/sql-ts#40]
Is it possible to use a module like pluralize to singularize table names rather than simply removing the 's'?

Just removing the 's' works well in a lot of cases, but for a word like, say 'Addresses', it requires further manual configuration.

If not, maybe providing a custom API for generating table names?

**Comment by rmp135** [comment]
You can use the library to generate an object, map the columns to new names and generate the typescript.

```js
import sqlts from '@rmp135/sql-ts'

const schema = { ... }

const db = await sqlts.toObject(schema)
for (const table of db.tables) {
  for (const column of table.columns) {
    column.propertyName = column.name + "s"
  }
}
const script = sqlts.fromObject(db, schema)
console.log(script)
```

I may remove the pluralisation entirely in a future version. Different languages and edge cases makes it likely to not work in all circumstances, as you've found. With the above, everyone can configure it their own way.

**Comment by Bradleykingz** [comment]
That addresses my problem well enough, thanks.
