### ISSUE TITLE
Cannot read property 'split' of undefined

### ISSUE THREAD

**Issue by ProtoCh4os** [rmp135/sql-ts#43]
This error happens on version 1.5.0, I tried installing version 1.3.0 and it worked.
Tried using both `npx` and as a module, using toTypescript and toObject, and all cases printed the same error:

`(node:11591) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'split' of undefined`

**Comment by rmp135** [comment]
Thanks for the report. Which database client are you experiencing this with?

**Comment by ProtoCh4os** [comment]
This case happened with Knex connecting with a SQL Server instance.

**Comment by rmp135** [comment]
Fixed in 1.5.1.
