### ISSUE TITLE
ENUM values are not correctly transformed

### ISSUE THREAD

**Issue by getsbydev** [rmp135/sql-ts#46]
In my postgres db I've got an "environment" enum defined with the values "TEST" and "LIVE".
After I generated the ts types, the output file shows me the enum like this:

`
export enum environment {
  0 = '[object Object]',
  1 = '[object Object]',
}
`

The desired output would be the following:
`
export enum environment {
  TEST = 0,
  LIVE = 1,
}
`

Also, acccording to the [TypeScript documentation](https://www.typescriptlang.org/docs/handbook/enums.html) ENUMs do not need quotes.

**Comment by rmp135** [comment]
Thanks for the report. This has been fixed in 1.5.2. The generated ENUMs require quotes as the values are taken directly from the database, this allows for using them as insert / update values.
