### ISSUE TITLE
Mark which columns are primary key.

### ISSUE THREAD

**Issue by santialbo** [rmp135/sql-ts#53]
I'm super happy I found this project because I am using a very similar script in my projects. [Here](https://gist.github.com/santialbo/6d5f00a8a8c0bbba2bfa42dc42287f6e) is it if you are interested in having a look.

I would love to get rid of it and use sql-ts instead but I'm missing a feature I have in my script which is to know which columns are the primary keys.

Do you think this is something that could be added as part of the `getAllColumns` function?

**Comment by rmp135** [comment]
Hey, sorry for the long delay. I've been thinking a lot about this issue and I'm not convinced yet I want to add it, it's verging a little away from my original intention of a simple type mapper. 

You might be able to use my module for the type mapping and fetch the primary keys yourself.

**Comment by santialbo** [comment]
Thanks for the answer. My original request wasnt' to change the overal behavior of this library, it was just to expose an `isPrimary` or similar on the ColumnDefinition so I can use it from a custom template.

**Comment by saostad** [comment]
Hi, that would be useful for my project too. 
I am generating Graphql schema from DB schema and the primary key is equivalent to type ID in Graphql

**Comment by rmp135** [comment]
Took me long enough but I've finally put it into release 1.8.0. `isPrimaryKey` is now on the object passed to the template. I've also updated the README to better illustrate what other values are passed into the template.

I've also bumped the version numbers so if it falls apart let me know.
