### ISSUE TITLE
Add lowercase and uppercase options to table / column / other names

### ISSUE THREAD

**Issue by brianmhunt** [rmp135/sql-ts#55]
Some (especially older) databases have poor naming conventions e.g. `tableid` and `TableID`.  It'd be great to homogenize this with a "lowercase" option (particularly for columns).

Looks like a change to [SharedTask.convertCase](https://github.com/rmp135/sql-ts/blob/master/src/SharedTasks.ts)?

**Comment by rmp135** [comment]
Sure thing. I'll add it to each of the conversion options.
