### ISSUE TITLE
Question: Add the original SQL type in the handlebars template

### ISSUE THREAD

**Issue by don1989** [rmp135/sql-ts#59]
Hi, thanks a lot for this great work!

I was wondering if there was a way to somehow include the original SQL type in the generated files as a comment alongside the type?

i.e. 

```
interface Table {
MyCol : string; // varchar(20)
MyCol2 : number; // smallint
...
}
```

**Comment by jacobjmarks** [comment]
Looks like the original type is exposed as part of the [`Column`](https://github.com/rmp135/sql-ts/blob/9acefccf85e59950c923324d8d45d9b0c3b2f19c/src/Typings.ts#L43) definition; populated as part of the [`getAllColumns`](https://github.com/rmp135/sql-ts/blob/9acefccf85e59950c923324d8d45d9b0c3b2f19c/src/Adapters/AdapterInterface.ts#L31) function of the relevant [database adapter](https://github.com/rmp135/sql-ts/tree/9acefccf85e59950c923324d8d45d9b0c3b2f19c/src/Adapters).

Try referencing this in your handlebars template within the `columns` loop as `{{type}}` ...

```handlebars
"{{propertyName}}": {{propertyType}} // {{type}}
```

**Comment by don1989** [comment]
Perfect, thank you @jacobjmarks
