### ISSUE TITLE
[Question] what's different between optional and nullable property for each column

### ISSUE THREAD

**Issue by saostad** [rmp135/sql-ts#61]
what's different between optional and nullable property for each column? 
the only thing I can imagine fields in DB that has a default value that is optional.
is that correct or anything else?

**Comment by ravshansbox** [comment]
@rmp135 primary keys can't be optional

**Comment by Seamus1989** [comment]
yeah why are they flagged as optional?

**Comment by ravshansbox** [comment]
At first I did not understand, then I realized the problem. Key point here is we need to have two interfaces for every record: one for typing reads and one for writes. For read results ids are never optional. But they are optional for writes as those fields are database generated.

**Comment by Seamus1989** [comment]
update the handlebars template file  with this on line 8
```
"{{propertyName}}"{{#if optional}}{{#if 'ID'}}{{else}}?{{/if}}{{/if}}: {{propertyType}} {{#if nullable}}| null {{/if}}
```
