### ISSUE TITLE
[bug] illegal characters allowed in SQL server for table names but not in typescript

### ISSUE THREAD

**Issue by saostad** [rmp135/sql-ts#71]
Hi,

table name "dbo.test-tbl01" is perfectly valid in SQL server but not in typescript, we can't have an interface name with "-" in the middle of the name so the generated code is broken. 
I tried "tableNameCasing": "pascal" flag but it didn't help.

**Comment by rmp135** [comment]
Ok. I think removing any alphanumeric characters will fix this. I'll also remove numbers at the beginning of the interface name as that's also not allowed. Hang tight for an update.

**Comment by saostad** [comment]
Hey, I just created a pull request to fix the problem. 
https://github.com/rmp135/sql-ts/pull/72
