### ISSUE TITLE
custom change-case function

### ISSUE THREAD

**Issue by xiaoyu-tamu** [rmp135/sql-ts#73]
The current camelcase will convert `ID` -> to `iD`, it would be nice to allow user provider custom change-case function in config,

```
{
  "columnNameCasing": name => customCamelCase(name),
}
```

**Comment by saostad** [comment]
Hey, 
I have PR #72  that will fix the issue.

**Comment by xiaoyu-tamu** [comment]
👍

**Comment by rmp135** [comment]
I've thought about this and I want to keep the configuration to be a plain JSON file which excludes functions. If you want more configuration over your schema output you can use [toObject](https://github.com/rmp135/sql-ts#toobject) to convert into an object, make the changes you want and [fromObject](https://github.com/rmp135/sql-ts#toobject) to generate the output file.
