### ISSUE TITLE
Support type mappings

### ISSUE THREAD

**Issue by thupi** [rmp135/sql-ts#8]
This is so udeful :-) 

I really like typescript and will really like to have my tables in MSSQL typed. This tool is exactly what i am looking for :-)  However, most of the types in my table is not supported. Would it be possible to find a way for user to map SQL types to typescript types :-) ?

Thanks for this tool :D !

**Comment by rmp135** [comment]
The [TypeMap.ts](https://github.com/rmp135/sql-ts/blob/master/src/TypeMap.ts) file controls how types are mapped between SQL and TypeScript. Do you have a list of the types that are missing?
You could also use the [TypeOverrides](https://github.com/rmp135/sql-ts#typeoverrides) settings to map individual columns.

**Comment by rmp135** [comment]
Pushed a new version (0.3.2) to allow for user defined type mappings. These mappings will be checked before the built in and mapped if found. Check the [README](https://github.com/rmp135/sql-ts#typemap) for further information.

**Comment by thupi** [comment]
@rmp135 The type i was haveing troubles with was MSSQL specific types such as smalldatatime and so on :-) 

Awesome, that makes this tool close to perfect in terms of using MSSQL with typescript :-D ! Thanks for the quick update :-)
