### ISSUE TITLE
Column name consisted of numbers turns into empty string

### ISSUE THREAD

**Issue by hwhang0917** [rmp135/sql-ts#82]
Using SQL Server given a following query:

```sql
CREATE TABLE SampleTable (
	testID varchar(100) NOT NULL,
	[0000] varchar(100),
	[1800] numeric(38,0)
);
```

creates a table with column name that begins with a number.

However this [line](https://github.com/rmp135/sql-ts/blob/8f761f78903aa6cc78b1943afc517184b06aa505/src/SharedTasks.ts#L13-L15) removes the entire column's property name to blank string resulting in duplicate type name of `''` as such:

```ts
export interface SampleTableEntity {
	'testID': string;
	''?: string | null;
	''?: number | null;
}
```
The commit that added the line was titled - [fix: removed illegal characters allowed in SQL server but not in type…
](https://github.com/rmp135/sql-ts/commit/377346be25bd17fa15b556b912350c27c634632a)

Isn't following type names allowed in TypeScript?
```ts
export interface SampleTableEntity {
	'testID': string;
	'0000'?: string | null;
	'1800'?: number | null;
}
```

**Comment by rmp135** [comment]
Thanks for that. Perhaps an early oversight before realising that the types could be quoted. I'll get a fix out for it.
