### ISSUE TITLE
Support for Postgres Views (non-materialized)

### ISSUE THREAD

**Issue by subwaymatch** [rmp135/sql-ts#87]
Hello.

Thank you for a very useful tool! 🙏 It seems that type generation for regular Postgres views is not supported yet. Is this due to a technical limitation or complexity?

**Comment by rmp135** [comment]
I don't use Postgres personally so I don't know exactly what features people use. It doesn't look difficult to add so I'll try and get it in the next release.

**Comment by subwaymatch** [comment]
@rmp135 Oh wow, that would be incredible. I'll be looking forward to the new release, thank you!

**Comment by rmp135** [comment]
Available in 1.11.0.
