### ISSUE TITLE
Enum entry order is unstable between database instances

### ISSUE THREAD

**Issue by jhiesey** [rmp135/sql-ts#88]
The order of keys within an enum is not consistent when running `sql-ts` on different postgres databases even if they have the same schema.

For example, one database might generate
```ts
export enum MyEnumType {
  'Value1': 'value1',
  'Value2': 'value2',
}
```
while another generates
```ts
export enum MyEnumType {
  'Value2': 'value2',
  'Value1': 'value1',
}
```

Postgres enums have a natural sort order, and it would be nice if the types followed that order. I quickly hacked up a temporary fix here: https://github.com/SocketDev/sql-ts/commit/e048dc280b08a8aa75185a5f60640a121169791c
but it's not very clean. Better would be to pass through the `enumsortorder` column and sort later, like with tables here: https://github.com/rmp135/sql-ts/blob/64ea54c9a5881af271eb19f4af281faaa5043cc1/src/DatabaseTasks.ts#L23

The order of enums in the output should also be deterministic, although I haven't run into a problem with that yet.

**Comment by jhiesey** [comment]
It turns out the order of enums themselves is also unstable in practice.
This should fix it: https://github.com/SocketDev/sql-ts/commit/5fe08c180bb9b8345cd55649c09fb2c5f9bc2a74

**Comment by rmp135** [comment]
Didn't realise the enums were sorted. I'll get a fix in for that, even if it just sorts them in a logical order as you've suggested.
