### ISSUE TITLE
Config option to make all properties required

### ISSUE THREAD

**Issue by Jiia** [rmp135/sql-ts#98]
Currently sql-ts generates interfaces that have all columns that have a default value marked as optional by `?`. This is a very useful feature when you're using the types to ensure you're writing into the database with correct types.

However when you're using the types for reading data, it quickly becomes a nuisance. For example you might want to read a row from table `product` and pass its column `category TEXT NOT NULL DEFAULT 'other'` to some function that accepts a string. When read from the database, the `category` will always be string, but since it has a default value the types generated by sql-ts make it `string | undefined`.

In my application I solved the issue by generating two sets of the same types, one for writing and one for reading. The "read types" have all their `?` removed, which is essentially the same as running each interface through `Required<T>`. I used regexp for this, which is a bit ugly.

I think making all the generated interfaces' properties required would be a useful configuration option.

**Comment by rmp135** [comment]
This has come up a few times so I might think about making the optionality more configurable. I tend to promote template based configurations if the options do not rely on database properties.

I've added some [better documentation](https://rmp135.github.io/sql-ts/#/?id=why-are-properties-optional) that outlines the solution of editing the template file. I've copied it below for convenience. 

- Copy the [`template.handlbars`](https://github.com/rmp135/sql-ts/blob/master/src/template.handlebars) file, removing the `{{#if optional}}?{{/if}}` from the property definition and use the `template` config option to specify the new template. This may require you to set the property to `null` on inserting to prevent TypeScript compaining.
- Alternatively, do the above with a second config file (e.g. `sql-ts-read.json`) that uses the `interfaceNameFormat` config option to rename interfaces to be be readable (e.g. `${table}ReadEntity`) to generate read models of the database. 

Let me know if this solution works for you.

**Comment by rmp135** [comment]
I've added two new config options to help with this.

**globalOptionality** for  specifying a global override to optionality.

- `optional`: The generated properties will be optional.
- `required`: The generated properties will be required.
- `dynamic`: The generated properties will match the optionality of the underlying column, essentially as it works now.

**columnOptionality** for specifying optionality on a per columns basis to help when dynamic doesn't return what you expect  (SQLite doesn't return enough info to determine if a column is optional so a best guess is made).

You'll find them in the next release!
