### ISSUE TITLE
PSQL enums with numerical values cause 'An enum member cannot have a numeric name' error

### ISSUE THREAD

**Issue by Jiia** [rmp135/sql-ts#99]
If you have a Postgres database with enums such as:

```sql
CREATE TYPE "db"."some_enum" AS ENUM ('1', '2', '3');
```

Then sql-ts 1.12.1 will output the type as:

```typescript
export enum some_enum  {
  '1': '1',
  '2': '2',
  '3': '3',
}
```

Which causes "An enum member cannot have a numeric name" error with TypeScript 4.5.5.

I used a workaround for the issue by using a custom template file and adding a `key_` prefix to the enum keys:
```handlebars
export enum {{convertedName}} {
{{#each values as |value|}}
  'key_{{value.convertedKey}}' = '{{value.value}}',
{{/each}}
}
```

I'm not sure if there's any obvious fix to the issue other than prefixing the keys. Maybe that should be the default behaviour?

**Comment by rmp135** [comment]
The only thing I can think of is similar to the above but specifically for numeric enum keys. 

I'll add a `enumNumericKeyFormat` option that allows for specifying a specific naming format when a numeric key is found, as some users may want to use a different convention. By default it will prepend with an underscore ('2' becomes '_2').
